In [1]:
import pandas as pd
import numpy as np
dt=pd.read_csv("practical2.csv")

In [2]:
dt

,math_score,reading_score,writing_score,placement_score,club_join_year,placement_offer_count,gender
0,62,81,60,87,2019,3,male
1,78,94,68,79,2019,2,male
2,68,92,70,80,2021,2,female
3,72,78,66,79,2019,2,female
4,75,91,75,81,2019,2,male
5,80,77,78,97,2020,3,male
6,77,76,72,86,2021,3,female
7,61,82,61,91,2020,3,male
8,79,91,80,82,2021,2,female
9,63,90,69,97,2021,3,male
10,71,83,64,100,2020,3,female
11,78,88,65,85,2018,3,male
12,78,81,80,95,2019,3,female
13,61,75,73,96,2021,3,female
14,62,95,73,75,2018,2,male
15,65,77,65,75,2021,2,female
16,61,82,63,79,2018,2,male
17,61,82,80,90,2020,3,female
18,66,91,64,84,2019,2,male
19,69,81,66,88,2020,3,female
20,78,83,73,80,2018,2,male
21,61,90,63,93,2020,3,female
22,68,88,69,86,2019,3,male
23,73,81,80,81,2018,2,female
24,70,94,79,99,2020,3,male
25,61,93,67,76,2019,2,female
26,79,95,61,96,2020,3,male
27,71,83,67,88,2020,3,female
28,77,84,73,97,2019,3,male
29,62,88,60,76,2021,2,female

In [3]:
dt['gender']=dt['gender'].map({'male':0,'female':1})

In [4]:
dt

,math_score,reading_score,writing_score,placement_score,club_join_year,placement_offer_count,gender
0,62,81,60,87,2019,3,0
1,78,94,68,79,2019,2,0
2,68,92,70,80,2021,2,1
3,72,78,66,79,2019,2,1
4,75,91,75,81,2019,2,0
5,80,77,78,97,2020,3,0
6,77,76,72,86,2021,3,1
7,61,82,61,91,2020,3,0
8,79,91,80,82,2021,2,1
9,63,90,69,97,2021,3,0
10,71,83,64,100,2020,3,1
11,78,88,65,85,2018,3,0
12,78,81,80,95,2019,3,1
13,61,75,73,96,2021,3,1
14,62,95,73,75,2018,2,0
15,65,77,65,75,2021,2,1
16,61,82,63,79,2018,2,0
17,61,82,80,90,2020,3,1
18,66,91,64,84,2019,2,0
19,69,81,66,88,2020,3,1
20,78,83,73,80,2018,2,0
21,61,90,63,93,2020,3,1
22,68,88,69,86,2019,3,0
23,73,81,80,81,2018,2,1
24,70,94,79,99,2020,3,0
25,61,93,67,76,2019,2,1
26,79,95,61,96,2020,3,0
27,71,83,67,88,2020,3,1
28,77,84,73,97,2019,3,0
29,62,88,60,76,2021,2,1

In [10]:
m=v_dt['math_score'].mean()
dt['math_score'].fillna(value=m_v,inplace=True)
dt

NameError: name 'v_dt' is not defined